# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-15 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akademik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nilai', models.IntegerField(blank=True, max_length=5, null=True)),
                ('siswa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siswas', to='orm.Siswa')),
            ],
        ),
    ]
