# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-15 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_auto_20180915_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akademik',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='akademik',
            table='Akademik',
        ),
    ]
