# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-15 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0005_auto_20180915_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akademik',
            name='nama',
            field=models.CharField(max_length=100),
        ),
    ]
