# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-16 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_auto_20180916_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hasiltes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nilai', models.IntegerField(default=5)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasiltess', to='orm.Siswa')),
            ],
            options={
                'db_table': 'Hasiltes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Karakter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sikap', models.CharField(blank=True, max_length=100, null=True)),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orm.Siswa')),
            ],
            options={
                'db_table': 'Karakter',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('jenjang', models.CharField(blank=True, max_length=100, null=True)),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orm.Siswa')),
            ],
            options={
                'db_table': 'Kelas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Plomba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensitas', models.CharField(blank=True, max_length=100, null=True)),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orm.Siswa')),
            ],
            options={
                'db_table': 'Plomba',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='akademik',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akademiks', to='orm.Siswa'),
        ),
    ]
