# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-16 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0008_auto_20180916_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karakter',
            name='sikap',
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='jenjang',
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='plomba',
            name='intensitas',
        ),
        migrations.AddField(
            model_name='karakter',
            name='baik',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='karakter',
            name='buruk',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='karakter',
            name='cukup_baik',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='kelas',
            name='kelas_1',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='kelas',
            name='kelas_2',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='kelas',
            name='kelas_3',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='plomba',
            name='cukup_sering',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='plomba',
            name='jarang',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='plomba',
            name='sering',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='plomba',
            name='tidak_pernah',
            field=models.IntegerField(default=5),
        ),
    ]
