# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-18 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0011_auto_20180916_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karakter',
            old_name='baik',
            new_name='nilai',
        ),
        migrations.RenameField(
            model_name='kelas',
            old_name='kelas_1',
            new_name='nilai',
        ),
        migrations.RenameField(
            model_name='plomba',
            old_name='cukup_sering',
            new_name='nilai',
        ),
        migrations.RemoveField(
            model_name='karakter',
            name='buruk',
        ),
        migrations.RemoveField(
            model_name='karakter',
            name='cukup_baik',
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='kelas_2',
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='kelas_3',
        ),
        migrations.RemoveField(
            model_name='plomba',
            name='jarang',
        ),
        migrations.RemoveField(
            model_name='plomba',
            name='sering',
        ),
        migrations.RemoveField(
            model_name='plomba',
            name='tidak_pernah',
        ),
        migrations.AddField(
            model_name='karakter',
            name='sikap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kelas',
            name='jenjang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plomba',
            name='intensitas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hasiltes',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
