# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-24 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0012_auto_20180918_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akademik',
            name='siswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='akademiks', to='orm.Siswa'),
        ),
        migrations.AlterField(
            model_name='hasiltes',
            name='siswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasiltess', to='orm.Siswa'),
        ),
        migrations.AlterField(
            model_name='karakter',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karakters', to='orm.Siswa'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kelass', to='orm.Siswa'),
        ),
        migrations.AlterField(
            model_name='plomba',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plombas', to='orm.Siswa'),
        ),
    ]
