# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-24 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0014_auto_20180924_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='akademik',
            old_name='nama',
            new_name='matapelajaran',
        ),
    ]
