# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-24 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0015_auto_20180924_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akademik',
            name='siswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='akademika', to='orm.Siswa'),
        ),
    ]
