# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-24 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0016_auto_20180924_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biologi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
                ('siswa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biologis', to='orm.Siswa')),
            ],
            options={
                'db_table': 'Biologi',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Fisika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
                ('siswa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fisikas', to='orm.Siswa')),
            ],
            options={
                'db_table': 'Fisika',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HasilTes_Biologi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
                ('siswa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasiltes_biologis', to='orm.Siswa')),
            ],
            options={
                'db_table': 'HasilTes_Biologi',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HasilTes_Fisika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
                ('siswa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasiltes_fisikas', to='orm.Siswa')),
            ],
            options={
                'db_table': 'HasilTes_Fisika',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HasilTes_Kimia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
                ('siswa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasiltes_kimias', to='orm.Siswa')),
            ],
            options={
                'db_table': 'HasilTes_Kimia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HasilTes_Matematika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
                ('siswa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasiltes_matematikas', to='orm.Siswa')),
            ],
            options={
                'db_table': 'HasilTes_Matematika',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Kimia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
                ('siswa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kimias', to='orm.Siswa')),
            ],
            options={
                'db_table': 'Kimia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Matematika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
                ('siswa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matematikas', to='orm.Siswa')),
            ],
            options={
                'db_table': 'Matematika',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='akademik',
            name='siswa',
        ),
        migrations.RemoveField(
            model_name='hasiltes',
            name='siswa',
        ),
        migrations.AlterField(
            model_name='kelas',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kelass', to='orm.Siswa'),
        ),
        migrations.DeleteModel(
            name='Akademik',
        ),
        migrations.DeleteModel(
            name='Hasiltes',
        ),
    ]
