# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-25 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0018_auto_20180925_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='jenis_kelamin',
            field=models.CharField(choices=[('PR', 'Pria'), ('WN', 'Wanita')], default='PR', max_length=2),
        ),
    ]
