# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-29 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0020_auto_20180928_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matematika',
            name='nilai',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
