# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0023_auto_20181002_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilTes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
                ('siswa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasiltess', to='orm.Siswa')),
            ],
            options={
                'db_table': 'HasilTes',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='hasiltes_matematika',
            name='siswa',
        ),
        migrations.DeleteModel(
            name='HasilTes_Matematika',
        ),
    ]
