# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-04 08:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orm', '0025_auto_20181003_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesOlimpiade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('no', models.IntegerField(default=0)),
                ('gambar', models.ImageField(blank=True, help_text='Upload Foto Soal Anda', null=True, upload_to='gambar')),
                ('pertayaan', models.TextField(blank=True, null=True)),
                ('jawabanA', models.CharField(blank=True, max_length=50, null=True)),
                ('jawabanB', models.CharField(blank=True, max_length=50, null=True)),
                ('jawabanC', models.CharField(blank=True, max_length=50, null=True)),
                ('jawabanD', models.CharField(blank=True, max_length=50, null=True)),
                ('kunci', models.CharField(blank=True, max_length=50, null=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TesOlimpiade',
                'ordering': ['id'],
            },
        ),
    ]
