# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-10 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0026_tesolimpiade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesolimpiade',
            name='User',
        ),
        migrations.RemoveField(
            model_name='testbiologi',
            name='user',
        ),
        migrations.DeleteModel(
            name='TesOlimpiade',
        ),
        migrations.DeleteModel(
            name='testbiologi',
        ),
    ]
