# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-10 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0027_auto_20181010_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesOlimpiade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('gambar', models.ImageField(blank=True, help_text='Upload Foto Soal Anda', null=True, upload_to='gambar')),
                ('pertayaan', models.TextField(blank=True, null=True)),
                ('jawabanA', models.CharField(blank=True, max_length=50, null=True)),
                ('jawabanB', models.CharField(blank=True, max_length=50, null=True)),
                ('jawabanC', models.CharField(blank=True, max_length=50, null=True)),
                ('jawabanD', models.CharField(blank=True, max_length=50, null=True)),
                ('kunci', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'TesOlimpiade',
                'ordering': ['id'],
            },
        ),
    ]
