# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-12 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0029_auto_20181010_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesolimpiade',
            name='user',
        ),
        migrations.AddField(
            model_name='tesolimpiade',
            name='jawabanE',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tesolimpiade',
            name='jawabanA',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tesolimpiade',
            name='jawabanB',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tesolimpiade',
            name='jawabanC',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tesolimpiade',
            name='jawabanD',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tesolimpiade',
            name='kunci',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
