# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-14 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import orm.FileUploader


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0030_auto_20181012_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesolimpiade',
            name='gambar',
            field=models.ImageField(blank=True, help_text='Upload Foto Soal Anda', null=True, upload_to=orm.FileUploader.file_foto),
        ),
    ]
