# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-15 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0037_auto_20181015_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesolimpiade',
            name='gambar',
            field=models.ImageField(blank=True, default='../media/gambar/a.png', help_text='Upload Foto Soal Anda', null=True, upload_to='gambar'),
        ),
    ]
