# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-19 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0039_siswa_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siswa',
            old_name='email',
            new_name='nama_panggilan',
        ),
    ]
