# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-19 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0040_auto_20181019_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siswa',
            old_name='nama_panggilan',
            new_name='email',
        ),
    ]
