# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0041_auto_20181019_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bobot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_akademik', models.IntegerField(default=0)),
                ('hasil_tes', models.IntegerField(default=0)),
                ('kelas', models.IntegerField(default=0)),
                ('karakter', models.IntegerField(default=0)),
                ('plomba', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Bobot',
                'ordering': ['id'],
            },
        ),
    ]
