# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0045_remove_bobot_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobot',
            name='hasil_tes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bobot',
            name='karakter',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bobot',
            name='kelas',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bobot',
            name='nilai_akademik',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bobot',
            name='plomba',
            field=models.FloatField(default=0),
        ),
    ]
