# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-31 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0046_auto_20181030_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='jenjang',
            field=models.CharField(choices=[('1 SMA', '1 SMA'), ('2 SMA', '2 SMA'), ('3 SMA', '3 SMA')], default='1 SMA', max_length=5),
        ),
    ]
