# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-31 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0047_auto_20181031_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='jenjang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
