# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-01 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orm', '0048_auto_20181031_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilTes_F',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'HasilTes_F',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HasilTes_K',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'HasilTes_K',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HasilTes_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'HasilTes_M',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Karakter_F',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sikap', models.CharField(blank=True, max_length=100, null=True)),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Karakter_F',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Karakter_K',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sikap', models.CharField(blank=True, max_length=100, null=True)),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Karakter_K',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Karakter_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sikap', models.CharField(blank=True, max_length=100, null=True)),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Karakter_M',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Kelas_F',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(blank=True, max_length=100, null=True)),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Kelas_F',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Kelas_K',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(blank=True, max_length=100, null=True)),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Kelas_K',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Kelas_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(blank=True, max_length=100, null=True)),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Kelas_M',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NilaiAkademik_F',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Nilai_AkademikF',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NilaiAkademik_K',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Nilai_Akademik_K',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NilaiAkademik_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Nilai_Akademik_M',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Plomba_F',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensitas', models.CharField(blank=True, max_length=100, null=True)),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Plomba_F',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Plomba_K',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensitas', models.CharField(blank=True, max_length=100, null=True)),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Plomba_K',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Plomba_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensitas', models.CharField(blank=True, max_length=100, null=True)),
                ('nilai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Plomba_M',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Siswa_F',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('PR', 'Pria'), ('WN', 'Wanita')], default='PR', max_length=2)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('tanggal_lahir', models.DateField()),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Siswa_F',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Siswa_K',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('PR', 'Pria'), ('WN', 'Wanita')], default='PR', max_length=2)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('tanggal_lahir', models.DateField()),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Siswa_K',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Siswa_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('PR', 'Pria'), ('WN', 'Wanita')], default='PR', max_length=2)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('tanggal_lahir', models.DateField()),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Siswa_M',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TesOlimpiade_F',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('gambar', models.ImageField(blank=True, default='../media/gambar/a.png', help_text='Upload Foto Soal Anda', null=True, upload_to='gambar')),
                ('pertayaan', models.TextField(blank=True, null=True)),
                ('jawabanA', models.CharField(blank=True, max_length=200, null=True)),
                ('jawabanB', models.CharField(blank=True, max_length=200, null=True)),
                ('jawabanC', models.CharField(blank=True, max_length=200, null=True)),
                ('jawabanD', models.CharField(blank=True, max_length=200, null=True)),
                ('jawabanE', models.CharField(blank=True, max_length=200, null=True)),
                ('kunci', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'TesOlimpiade_F',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TesOlimpiade_K',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('gambar', models.ImageField(blank=True, default='../media/gambar/a.png', help_text='Upload Foto Soal Anda', null=True, upload_to='gambar')),
                ('pertayaan', models.TextField(blank=True, null=True)),
                ('jawabanA', models.CharField(blank=True, max_length=200, null=True)),
                ('jawabanB', models.CharField(blank=True, max_length=200, null=True)),
                ('jawabanC', models.CharField(blank=True, max_length=200, null=True)),
                ('jawabanD', models.CharField(blank=True, max_length=200, null=True)),
                ('jawabanE', models.CharField(blank=True, max_length=200, null=True)),
                ('kunci', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'TesOlimpiade_K',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TesOlimpiade_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('gambar', models.ImageField(blank=True, default='../media/gambar/a.png', help_text='Upload Foto Soal Anda', null=True, upload_to='gambar')),
                ('pertayaan', models.TextField(blank=True, null=True)),
                ('jawabanA', models.CharField(blank=True, max_length=200, null=True)),
                ('jawabanB', models.CharField(blank=True, max_length=200, null=True)),
                ('jawabanC', models.CharField(blank=True, max_length=200, null=True)),
                ('jawabanD', models.CharField(blank=True, max_length=200, null=True)),
                ('jawabanE', models.CharField(blank=True, max_length=200, null=True)),
                ('kunci', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'TesOlimpiade_M',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='plomba_m',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plomba_ms', to='orm.Siswa_M'),
        ),
        migrations.AddField(
            model_name='plomba_k',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plomba_ks', to='orm.Siswa_K'),
        ),
        migrations.AddField(
            model_name='plomba_f',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plomba_fs', to='orm.Siswa_F'),
        ),
        migrations.AddField(
            model_name='nilaiakademik_m',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nilai_akademik_ms', to='orm.Siswa_M'),
        ),
        migrations.AddField(
            model_name='nilaiakademik_k',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nilai_akademik_ks', to='orm.Siswa_K'),
        ),
        migrations.AddField(
            model_name='nilaiakademik_f',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nilai_akademik_fs', to='orm.Siswa_F'),
        ),
        migrations.AddField(
            model_name='kelas_m',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kelas_ms', to='orm.Siswa_M'),
        ),
        migrations.AddField(
            model_name='kelas_k',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kelas_ks', to='orm.Siswa_K'),
        ),
        migrations.AddField(
            model_name='kelas_f',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kelas_fs', to='orm.Siswa_F'),
        ),
        migrations.AddField(
            model_name='karakter_m',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karakter_ms', to='orm.Siswa_M'),
        ),
        migrations.AddField(
            model_name='karakter_k',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karakter_ks', to='orm.Siswa_K'),
        ),
        migrations.AddField(
            model_name='karakter_f',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karakter_fs', to='orm.Siswa_F'),
        ),
        migrations.AddField(
            model_name='hasiltes_m',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasiltes_ms', to='orm.Siswa_M'),
        ),
        migrations.AddField(
            model_name='hasiltes_k',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasiltes_ks', to='orm.Siswa_K'),
        ),
        migrations.AddField(
            model_name='hasiltes_f',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasiltes_fs', to='orm.Siswa_F'),
        ),
    ]
