# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-03 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0052_auto_20181103_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasiltes',
            name='mata_pelajaran',
            field=models.CharField(choices=[('biologi', 'Biologi'), ('fisika', 'Fisika'), ('kimia', 'Kimia'), ('matematika', 'Matematika')], default='biologi', max_length=10),
        ),
        migrations.AddField(
            model_name='karakter',
            name='mata_pelajaran',
            field=models.CharField(choices=[('biologi', 'Biologi'), ('fisika', 'Fisika'), ('kimia', 'Kimia'), ('matematika', 'Matematika')], default='biologi', max_length=10),
        ),
        migrations.AddField(
            model_name='kelas',
            name='mata_pelajaran',
            field=models.CharField(choices=[('biologi', 'Biologi'), ('fisika', 'Fisika'), ('kimia', 'Kimia'), ('matematika', 'Matematika')], default='biologi', max_length=10),
        ),
        migrations.AddField(
            model_name='nilaiakademik',
            name='mata_pelajaran',
            field=models.CharField(choices=[('biologi', 'Biologi'), ('fisika', 'Fisika'), ('kimia', 'Kimia'), ('matematika', 'Matematika')], default='biologi', max_length=10),
        ),
        migrations.AddField(
            model_name='plomba',
            name='mata_pelajaran',
            field=models.CharField(choices=[('biologi', 'Biologi'), ('fisika', 'Fisika'), ('kimia', 'Kimia'), ('matematika', 'Matematika')], default='biologi', max_length=10),
        ),
        migrations.AddField(
            model_name='tesolimpiade',
            name='mata_pelajaran',
            field=models.CharField(choices=[('biologi', 'Biologi'), ('fisika', 'Fisika'), ('kimia', 'Kimia'), ('matematika', 'Matematika')], default='biologi', max_length=10),
        ),
    ]
