# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-04 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0053_auto_20181103_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobot',
            name='hasil_tes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bobot',
            name='karakter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bobot',
            name='kelas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bobot',
            name='nilai_akademik',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bobot',
            name='plomba',
            field=models.IntegerField(default=0),
        ),
    ]
