# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-09 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0054_auto_20181104_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plomba',
            name='intensitas',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
