# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-13 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0056_soalbiologi_soalfisika_soalkimia_soalmatematika'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soalbiologi',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='soalfisika',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='soalkimia',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='soalmatematika',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='soalbiologi',
            table='SoalBiologi',
        ),
        migrations.AlterModelTable(
            name='soalfisika',
            table='SoalFisika',
        ),
        migrations.AlterModelTable(
            name='soalkimia',
            table='SoalKimia',
        ),
        migrations.AlterModelTable(
            name='soalmatematika',
            table='SoalMatematika',
        ),
    ]
