# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-14 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0057_auto_20181113_0705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soalbiologi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='soalfisika',
            options={},
        ),
        migrations.AlterModelOptions(
            name='soalkimia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='soalmatematika',
            options={},
        ),
        migrations.AlterModelTable(
            name='soalbiologi',
            table=None,
        ),
        migrations.AlterModelTable(
            name='soalfisika',
            table=None,
        ),
        migrations.AlterModelTable(
            name='soalkimia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='soalmatematika',
            table=None,
        ),
    ]
