# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-14 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0058_auto_20181114_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='soalbiologi',
            name='nama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='soalfisika',
            name='nama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='soalkimia',
            name='nama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='soalmatematika',
            name='nama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
