# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-16 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0060_auto_20181116_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='email',
        ),
    ]
