# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-16 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0061_remove_siswa_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='tanggal_lahir',
        ),
    ]
