# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-21 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import orm.FileUploader


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0062_remove_siswa_tanggal_lahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesolimpiade',
            name='gambar',
            field=models.ImageField(blank=True, default='../media/gambar/a.png', help_text='Upload Foto Soal Anda', null=True, upload_to=orm.FileUploader.file_foto),
        ),
    ]
