# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-21 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0064_auto_20181121_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesolimpiade',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
